global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8005']

  - job_name: 'attendance-service'
    static_configs:
      - targets: ['attendance-service:8001']

  - job_name: 'food-service'
    static_configs:
      - targets: ['food-service:8002']
